name: CI/CD to PythonAnywhere

on: 
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib streamlit

    - name: Run Streamlit app locally (for testing)
      run: |
        streamlit run app.py &

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to PythonAnywhere
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'www.pythonanywhere.com'
        username: AnirudhMojo
        api-token: ${{ secrets.PA_API_TOKEN }}
        domain-name: AnirudhMojo.pythonanywhere.com
